### ISSUE TITLE
Can't access admin after setup: "Your browser doesn't support cookies"

### ISSUE THREAD

**Issue by kermie** [OXID-eSales/oxvm_eshop#27]
After a completely new setup I want to enter the admin panel. Login is refused saying "Error: your browser doesn't support cookies" - of course, this is not true.

The appropriate language key, LOGIN_NO_COOKIE_SUPPORT, can be found in 
application/controllers/admin/login.php
application/views/admin/{locale}/lang.php
application/views/flow/{locale}/lang.php as well as in tmp/ files

After cleaning up tmp/ I can login properly.

As far as I can see,
* content of the folder tmp/ shall go to .gitignore and
* as there's no functional call, the lang key shall be deleted from flow theme lang file

**Comment by rezonanc-oxid** [comment]
There are few things I would like to double-check before taking action:

* Before running the provision process, was the `tmp` folder clean?
* What is the desired behaviour? The provision process should tackle with the shared folder and delete all files from `tmp` folder?

**Comment by kermie** [comment]
This actually happened after _vagrant destroy_ and _vagrant up_ again. So the `tmp` folder seems to be not clean when setting up a new machine.

Desired behaviour:
* the `tmp` should be clean so no error message can come up when trying to log in in admin panel

**Comment by rezonanc-oxid** [comment]
I would like to remind the concept of shared folder, it's shared because it uses the data from your host machine so that it could persist even after the VM/guest machine is down.
Just imagine a case that developer works on a feature, he forgot to save it in VCS and then after electricity loss (just an example) the VM has halted, after that the changes would be lost. That's not something to be desired.
On the other hand `tmp` folder is safe to be deleted on VM start (at least I see no reason not to do so) so I'll treat this as a feature request. Will update it when I will have time for that.

**Comment by kermie** [comment]
Okay, got the concept now. I expected everything to be destroyed if "destroy" is used in a command :-)
So - no bug nor feature request necessary. Cheers!
