### ISSUE TITLE
Use .local instead of .dev 

### ISSUE THREAD

**Issue by roman-1983** [OXID-eSales/oxvm_eshop#4]
.dev is an official TLD since summer 2014 an causes some DNS problems, especially under windows-systems. Better use .local als domain.

**Comment by rezonanc-oxid** [comment]
Thanks for the tip! I tried to research about it and was able to find out that this TLD was bought by Google. But I failed to to find a reason why having 'www.oxideshop.dev' domain could be problematic to access the installation of local eShop. This is written directly to host machine's `hosts` file which should override any responses from DNS servers.

Could you provide an example/situation where this setting would fail?

In case this would be a major issue for a small group of users, there is always a way to override this setting via `vagrant_local.vm.hostname` and `vagrant_local.vm.aliases`.

What do you think?

**Comment by floeschie** [comment]
```.local``` is used by Active Directory environments:

https://en.wikipedia.org/wiki/.local

Found an interesting discussion here:

https://serverfault.com/questions/17255/top-level-domain-domain-suffix-for-private-network

We could use ```.lan```, ```.vm``` or ```.ox``` instead :)

**Comment by roman-1983** [comment]
Hi Edvinas,
the problem with the .dev domain is, that i have set up a DNS-Server which promotes the vm-domains to all clients in the intern network, so that my colleagues could see my vm and the running projects on it.

Windows started to get dns-problems because the ping to the .dev domains lead to 127.0.53.53 instead of the real IP because they are not entered in the `hosts` file but are shared via the local dns server.

**Comment by rezonanc-oxid** [comment]
I would say that your case is quite unique.

Just to double-check, will it help you/solve your issues to change VM's TLD from `.dev` to `.local` ?

If the answer is yes, are there any problems to change this via `vagrant_local.vm.hostname` and `vagrant_local.vm.aliases` configuration options inside `personal.yml`?

Quick example: https://github.com/OXID-eSales/oxvm_eshop#change-virtual-host

**Comment by roman-1983** [comment]
Could be a unique problem but it seems to me bad style to use a tld that exists for local development. ;-)

i'll close this issue because it is more a nice meant tip than an error. ;-)

**Comment by keywan-ghadami-oxid** [comment]
Using .local for a while now in projects, it seams to be the best solution if you like to make sure that requests staying​ local.

**Comment by roman-1983** [comment]
I have re-opened this issue because it looks like we can discuss again about that ;-)

**Comment by rezonanc-oxid** [comment]
I would prefer to have results instead of discussions. From MPOV I don't see any changes which would be necessary to be done NOW. Is the domain `oxideshop.dev` actually registered? To my knowledge - no. But let's verify that:

```
dig @8.8.8.8 oxideshop.dev | grep -A 1 "ANSWER SECTION" | grep -v "ANSWER SECTION"
oxideshop.dev.		3599	IN	A	127.0.53.53
```

It appears not to be registered yet. The entry of `127.0.53.53` points to TLD to be registered, yes, but not the actual FQDN, so by using the mentioned domain we're not blocking anyone from access to some Internet site which might be registered under this domain.

If there's a problem of using the default suggested domain everyone has the ability to change it in their `personal.yml` file, more information on how it can be done: https://github.com/OXID-eSales/oxvm_eshop#change-virtual-host 

You can also choose different TLD, there is nothing in configuration which restricts from doing that.

You might think that in order to "solve" this issue it's just enough to update the default configuration, unfortunately that's not the case. By changing the default domain name we will create more additional work for others compared to the benefit that we will get from this change. E.g. there are already a lot of references to the default domain name which is used ATM and if this reference will be in a non-working state it will create an impression that something is not working at all, which is something we would try to avoid.

So to very shortly summarise - the **needed effort** to update every possible reference to the default domain used in this project does not out-weight the benefit that we will get.

**Comment by alfredbez** [comment]
I'd change the default hostname from `.dev` to `.local` and add an alias.
```diff
diff --git a/ansible/vars/oxideshop.yml b/ansible/vars/oxideshop.yml
index caa0abd..fbe31be 100644
--- a/ansible/vars/oxideshop.yml
+++ b/ansible/vars/oxideshop.yml
@@ -2,8 +2,10 @@
 vagrant_local:
   vm:
     name: oxideshop
-    hostname: oxideshop.dev
+    hostname: oxideshop.local
     aliases:
+      - www.oxideshop.local
+      - oxideshop.dev
       - www.oxideshop.dev
     app_shared_folder:
       source: oxideshop
```

**Comment by alfredbez** [comment]
take a look at d0c0f6e681f8733a0e4b4a6f24ab167ad84f9e7b in #36

**Comment by rezonanc-oxid** [comment]
Seems like a nice compromise that would satisfy both sides! There's one thing I still need to verify internally, if that works, I see no problems to merge this. Thanks! I guess I will re-open the issue and keep everyone informed about the status.
