### ISSUE TITLE
System health check error is shown in eShop Admin interface

### ISSUE THREAD

**Issue by acirtautas** [OXID-eSales/oxvm_eshop#5]
After a fresh VM set-up as error is shown in eShop admin interface:

    System health check shows setup/server setup of this OXID eShop might be broken. 
    Probably this  OXID eShop behaves strange in some cases. 
    Please fix this as soon as possible.
    Support for fixing find in system health check.
    Please delete directory: setup!
    Due to security reasons put your config.inc.php file to read-only mode!"

Following the __"system health check"__ link, an error sign is displayed next to __"[Files/folders access rights](http://wiki.oxidforge.org/Installation#Files_.26_Folder_Permission_Setup])"__

**Comment by rezonanc-oxid** [comment]
I would like to point out that this information is relevant only if the eShop is being run in the production environment. Since this is a development environment, it safe to ignore these messages.

By the way, our development environment actually relies on having `setup/` folder present so that `reset-shop` script and testing library could work properly.

Regarding `config.inc.php` it is wise to put it in read-only mode, but for development purpose it's a bit meaningless to do so.
